### ISSUE TITLE
dot product of two vectors

### ISSUE THREAD

**Issue by ylffan** [adtzlr/ttb#14]
Hi @adtzlr ,
I got unexpected results when I tried to use dot_11 to calculate dot product of two vectors.
I think it should be
dot_11 = dot_11 + T1%a(i)*T2%a(i)
instead of 
dot_11 = dot_11 + T1%a(i)*T2%a(j)

Please correct me if I am wrong.
![image](https://user-images.githubusercontent.com/60798575/85216594-5dc46c00-b354-11ea-9da7-138a71df87f1.png)

**Comment by adtzlr** [comment]
Of course you're right. Will fix it as soon as possible. Thanks!
