### ISSUE TITLE
toolbox logo and citation

### ISSUE THREAD

**Issue by jfriedlein** [adtzlr/ttb#16]
Hi Andreas @adtzlr ,
I don't want to hold you up, so the following is absolutely not a priority (just nice to have). However, would you mind giving me a Go/Nogo answer soon?

For an upcoming presentation I would like to refer to the ttb (and advertise it). Just for the fun I played around with a logo some time ago, because I think we're still missing one for the toolbox (always nicer than showing a written URL).
This is what I came up with (editable .svg file appended):
![ttb logo](https://user-images.githubusercontent.com/58786257/92444201-d2b87c80-f1b2-11ea-9373-809609ab2552.png)
I just wanted to check in with you, whether I may use this logo for the time being. Of course, it's your toolbox, you decide and we can alter the logo to your liking.

Another question that arises in this context, is how the toolbox could be cited (others for instance: https://www.tensortoolbox.org/, https://sites.google.com/site/aenader/umat-workshop). But that does not need to be elaborated in the near future.

Thanks and once again, lots of appreciation for the work you've put into the toolbox, it facilitates and improves my work majorly,
Johannes

PNG and SVG:
[ttb logo.zip](https://github.com/adtzlr/ttb/files/5186683/ttb.logo.zip)

**Comment by adtzlr** [comment]
Hi Johannes,

thank you for your ideas! As you've probably already guessed my time for this project tends to zero right now. I'll try to do my best to fix bugs if there are any in the near future. For citation I'm going to set up a DOI reference on zenodo and I will include a "how to cite" in the readme & documentation. Feel free to use whatever logo you would like in the near future for your presentations - I think I will keep things simple and use no "official" logo at all.

Glad you like the project! You should also thank Christoph Naumann as his hint on fortran programming in his dissertation inspired me to write this little toolbox.

**Comment by adtzlr** [comment]
I created a DOI for Version 1.0.0:  [![DOI](https://zenodo.org/badge/112017005.svg)](https://zenodo.org/badge/latestdoi/112017005) 

I'll leave this issue open for the logo discussion.
