### ISSUE TITLE
Does the lib support 2D calculations?

### ISSUE THREAD

**Issue by chuang05** [adtzlr/ttb#17]
Does the lib support 2D calculations?

**Comment by adtzlr** [comment]
Hi @chuang05! Sadly, no. And I do not plan to implement it explicitly. If you would like to perfom calculations in 2D you would have to 

**1. "expand" your input arrays to 3D,**
2. convert it to tensors,
3. do all calculations you would like to,
4. convert your tensors back to arrays,
**5. slice arrays to fit 2D array dimensions.**

So step 1. and 5. are additionally needed compared to 3D calculations. Of course there is some overhead inside the 3D tensor operations. 

You could write your own "as2darray" function similar to ["as Array"](https://adtzlr.github.io/ttb/functions/asarray.html).

Hope that helps.!
Best regards, Andreas

**Comment by chuang05** [comment]
OK, I see, thank you very much!

**Comment by chuang05** [comment]
> Hi @chuang05! Sadly, no. And I do not plan to implement it explicitly. If you would like to perfom calculations in 2D you would have to
> 
> **1. "expand" your input arrays to 3D,**
> 2. convert it to tensors,
> 3. do all calculations you would like to,
> 4. convert your tensors back to arrays,
> **5. slice arrays to fit 2D array dimensions.**
> 
> So step 1. and 5. are additionally needed compared to 3D calculations. Of course there is some overhead inside the 3D tensor operations.
> 
> You could write your own "as2darray" function similar to ["as Array"](https://adtzlr.github.io/ttb/functions/asarray.html).
> 
> Hope that helps.!
> Best regards, Andreas

OK, I see, thank you very much!
