### ISSUE TITLE
Einstein summation

### ISSUE THREAD

**Issue by javad-rahmannezhad** [adtzlr/ttb#19]
Thank you for the valuable tensor library. Is Einstein summation included in it?

**Comment by adtzlr** [comment]
Hi, do you mean something like NumPy's `einsum`? (https://numpy.org/doc/stable/reference/generated/numpy.einsum.html) Unfortunately not.

**Comment by javad-rahmannezhad** [comment]
Yes, I mean it. Oh, sorry to hear that.

**Comment by adtzlr** [comment]
You could have a look here but actually I didn't try it by myself: https://github.com/pseewald/fortran-einsum-example
