### ISSUE TITLE
Question of Example umat_nh_ttb_simple.F

### ISSUE THREAD

**Issue by edwardXZ06** [adtzlr/ttb#21]
Hi, Andreas:

I have a couple questions for this umat example using ttb. 

First, have you tested running of this umat file on Abaqus? I am assuming not, because apparently the updated stress (STRESS) and constitutive tangent (DDSDDE) is not defined, despite they were assigned by s and d in your code. 

Secondly, since I was running the umat developed on my own but it always have convergent issues. I noticed you have an additional step to push forward to Jaumann tangent rate of Cauchy stress for Abaqus. In the past, I always understand the DDSDDE required by Abaqus can be approximated by dSdE, where S is the 2nd PK stress. However, it seems that should be dsigma/dD, where sigma is Cauchy stress and D is the displacement, Would you mind expand a little bit about how did you get the equation on line 60 of your example code. 

Best,

**Comment by adtzlr** [comment]
No, I have not tested it because I have no Abacus license as I wrote in your other Issue.

For Abaqus, don't use `asarray` - Abaqus has different voigt notation than this toolbox. Use `asabqarray` instead.

Regarding tangent calculation, see this document (section Neo-Hooke material): https://imechanica.org/files/Writing%20a%20UMAT.pdf

**Comment by adtzlr** [comment]
You mean this example does not work in Abaqus? Wow, thanks for reporting. I'll take a look on Monday. However, I can only double check the code - that's all I can do.

**Comment by adtzlr** [comment]
I think I found the error. Please rename the output variables from `s` to `stress` and `D` to `DDSDDE`. Will push a fix on Monday.

**Comment by edwardXZ06** [comment]
Yes, after redefine the DDSDDE, STRESS and detF1 in that code, everything works. Since I was trying to understand the DDSDDE by comparing my derivations with yours, and still have a couple question. I have read the document you mentioned, but that file doesn't help me much to compute DDSDDE from dS/dE. Therefore, I am wondering if you still have the derivation documents for this neo-hookean model implementation?

Also, I am wondering what's the difference between dya and cdya, literally you have explained it, but I didn't find any definition if I google "crossed dyadic product". While I have derivation written in tensor form, I just don't know when should I use dyadic and when should I use "crossed dyadic", since I didn't expand the tensors into indices notation. For me, all dyadic-like products look all like standard dyadic product.

**Comment by adtzlr** [comment]
> Yes, after redefine the DDSDDE, STRESS and detF1 in that code, everything works. 

Fine, thanks for testing it out!

> Since I was trying to understand the DDSDDE by comparing my derivations with yours, and still have a couple question. I have read the document you mentioned, but that file doesn't help me much to compute DDSDDE from dS/dE. Therefore, I am wondering if you still have the derivation documents for this neo-hookean model implementation?

Giving support for this library is one thing - I'll always try to help you! But I don't have the time (at least not now) to support you with your tensor calculations in detail. A little hint: All the FEA packages calculate a geometric tangent for you (a.k.a. "initial stress stiffness"), and for some historical reasons in so-called "updated lagrange" formulations they are requesting a so-called "Jaumann rate" of Kirchhoff or Cauchy stress. I think (!) the main reason behind this is to obtain symmetric tangent matrices for both the constitutive part inside UMAT and the internal calculated geometric stiffness.

Have a look at the pdf file isnide this repo from @mholla https://github.com/mholla/hitchhikers-guide-to-abaqus - I think this will be helpful to you!

All the best,
Andreas

**Comment by adtzlr** [comment]
> Also, I am wondering what's the difference between dya and cdya, literally you have explained it, but I didn't find any definition if I google "crossed dyadic product". While I have derivation written in tensor form, I just don't know when should I use dyadic and when should I use "crossed dyadic", since I didn't expand the tensors into indices notation. For me, all dyadic-like products look all like standard dyadic product.

Please have a look at the readme file:
* Dyadic Product C(i,j,k,l) = A(i,j) B(k,l) written as C = A.dya.B
* Crossed Dyadic Product C(i,j,k,l) = (A(i,k) B(j,l) + A(i,l) B(j,k))/2 written as C = A.cdya.B

Again, I can't help you when to use dyadic or outer products and crossed dyadic products. You have to know which product you would like to use. 

One example for crossed dyadic products are tensor derivatives w.r.t. the Tensor itself: https://en.wikipedia.org/wiki/Tensor_derivative_(continuum_mechanics)#Derivative%20of%20a%20second-order%20tensor%20with%20respect%20to%20itself

**Comment by adtzlr** [comment]
This issue was closed by my pull-request, feel free to open it again.
