### ISSUE TITLE
Initialisation of tensor components to zero

### ISSUE THREAD

**Issue by jfriedlein** [adtzlr/ttb#45]
While trying the new branch, I again noticed a change I did a while ago to my local implementation.

When defining the tensor types, I initialised all tensor components to zero, so that an uninitialised tensor is zero and its components are not undefined (numerically chaotic values). I was used to this from [deal.ii](https://dealii.org/current/doxygen/deal.II/classTensor.html#aeb8a775428e8c476cb85894c5839356e) and it might also protect other naive and innocent people like me. To initialise the components to zero, simply add "= 0." as shown below in the file `ttb_library.f`:

        type Tensor1
        ! tensor of rank 1
        real(kind=8), dimension(3) :: a = 0.
       end type Tensor1
       
       type Tensor2
        ! tensor of rank 2
        real(kind=8), dimension(3,3) :: ab = 0.
       end type Tensor2
       
       type Tensor2S
        ! symmetric tensor of rank 2 stored as vector
        real(kind=8), dimension(6) :: a6 = 0.
       end type Tensor2S
       
       type Tensor4
        ! tensor of rank 4
        real(kind=8), dimension(3,3,3,3) :: abcd = 0.
       end type Tensor4
       
       type Tensor4S
        ! symmetric tensor of rank 4 stored as 6x6 matrix
        real(kind=8), dimension(6, 6) :: a6b6 = 0.
       end type Tensor4S

This might be something to add, in case there is no reason against it?

**Comment by adtzlr** [comment]
Great idea, would you like to propose a PR? Otherwise, of course, I can do that too.

**Comment by jfriedlein** [comment]
I tried to create a PR. Currently my SmartGit is not working, so I did the PR via the browser. Let me know if the PR worked and is fine. I guess I missed linking the issue and the PR.
