### ISSUE TITLE
umat_nh_ttb_simple.f does not work in Abaqus

### ISSUE THREAD

**Issue by Jamal-dev** [adtzlr/ttb#48]
First error it gives at the line 'implicit none'. If I comment this line the code does not pop any error in Abaqus, but it gives NaN stress which should not be the case. 

It also gives this error in Log file.
"Begin Linking Abaqus/Standard User Subroutines
   Creating library standardU.lib and object standardU.exp
libirc.lib(fast_mem_ops.c.obj) : warning LNK4210: .CRT section exists; there may be unhandled static initializers or terminators
End Linking Abaqus/Standard User Subroutines"

What could be the problem?

**Comment by adtzlr** [comment]
Hi Jamal, thanks for the report! We need more informations. NaNs are also possible by your specific Umat code. 

Have you tried a very basic Umat, e.g. Linear-elastic or Neo-Hooke?

That could also be helpful: What version of `ttb` do you use?

**Comment by adtzlr** [comment]
The example is for Marc, not Abaqus. Abaqus does not support Total Lagrangian stress and elasticity tensors as far as I know.

**Comment by adtzlr** [comment]
It's quite a long time since I looked into the Docs of Abaqus. Probably the subroutine header is outdated? I'll have a look.

**Comment by adtzlr** [comment]
Instead of commenting out `implicit none`, could you please try to exclude the `aba_param.inc` line? Also please re-try with a bulk modulus of `kappa = 5.0`?

**Comment by Jamal-dev** [comment]
Hi @adtzlr ,
Thank you for your quick reply. I fixed the error. There was one typo error at line 61 `detF1`. It was supposed to be `J`. And also, `implicit none` should also be commented. However, even after the script starts working the result of stress was not matching with other subroutine provided by the Abaqus. So then I rewrite the code, and now it starts matching perfectly. I really like your repository. Here is the [code](https://github.com/Jamal-dev/ttb/blob/main/docs/examples/umat_neoHok_ttb.f). May be you can update the example.

**Comment by adtzlr** [comment]
Thank you for your positive feedback! If you'd like to contribute, you could also open a pull request. Otherwise I'll fix the example based on your solution.

FYI: I never had a full license for Abaqus - I wrote the example basically without testing. Then, some friends helped me out and tested it. Probably they corrected the mistakes on the fly and didn't give a feedback.

Once again, thank you!

**Comment by Jamal-dev** [comment]
That's inspiring to hear that you were able to provide an example without even having the required software.

Thank you for your code!! it made writing a code in Fortran easier and intuitive!

**Comment by adtzlr** [comment]
Okay, just for the records. The typo is here:

https://github.com/adtzlr/ttb/blob/f679b3719ec1cdf99afa5c2f8a48ab1dc5818ba4/docs/examples/umat_nh_ttb_simple.f#L60

the variable `detF1` is wrong, it should be `J` according to

https://github.com/adtzlr/ttb/blob/f679b3719ec1cdf99afa5c2f8a48ab1dc5818ba4/docs/examples/umat_nh_ttb_simple.f#L39
