### ISSUE TITLE
Implement Polar decomposition

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/ttb#54]
### Discussed in https://github.com/adtzlr/ttb/discussions/53

<div type='discussions-op-text'>

<sup>Originally posted by **Cyan2077** December 22, 2023</sup>
This toolbox is really nice. I have small suggestion that you can add the ' Polar decomposition' function  into this toolbox. Because when we edit UMAT in abaqus, if we use keyword 'orientation', the deformation tensor F will be passed in UMAT in local coordinate. We always need  'Polar decomposition'  to get the rotation part of the F, so that we can rotate the F back to the global coordinate. </div>

@Cyan2077 to be sure: you mean you have a deformation gradient $\boldsymbol{F}$ at hand and you would like to perform $\boldsymbol{F} = \boldsymbol{R} \boldsymbol{U}$, where $\boldsymbol{R}$ is the rotation matrix and $\boldsymbol{U}$ is the right stretch tensor? Are you interested in the left-polar decomposition $\boldsymbol{F} = \boldsymbol{V} \boldsymbol{R}$ too?

**Comment by adtzlr** [comment]
This is already nearly implemented. First step is to evaluate the right Cauchy-Green deformation tensor $\boldsymbol{C} = \boldsymbol{F}^T \boldsymbol{F}$, take its matrix square root $\boldsymbol{U} = \sqrt{\boldsymbol{C}}$ and finally obtain the rotation tensor from  $\boldsymbol{F} = \boldsymbol{R} \boldsymbol{U}$ as $\boldsymbol{R} = \boldsymbol{F} \boldsymbol{U}^{-1}$.

**Comment by Cyan2077** [comment]
Wow, thank you so much. If my paper is successful published, I must cite your code !

**Comment by adtzlr** [comment]
Glad you like it @Cyan2077! Did my comment already help you? We have holidays here in Austria, the Implementation will take one or two weeks.

**Comment by Cyan2077** [comment]
Of course, I have already fixed my problems. There is no rush. Have a nice trip ! Marry Christmas~

**Comment by adtzlr** [comment]
Hi,

I'll delay this because I'd have to use a subroutine instead of a function because of the multiple outputs. This toolbox contains only functions and I'd like to keep it simple. Please use this simple script as already described above:

```fortran
      type(Tensor2) :: F,R
      type(Tensor2s) :: C,U
      
      C = transpose(F)*F
      U = sqrt(C)
      R = F*inv(U)
```

I hope this is okay, I'll close this.

**Comment by adtzlr** [comment]
see also https://adtzlr.github.io/ttb/api/functions/squareroot.html
