### ISSUE TITLE
How can I use this in CalculiX?

### ISSUE THREAD

**Issue by nithinadidela** [adtzlr/ttb#9]
Hi, My work involves using St. Venant-Kirchoff material. How can I use this subroutine in my CalculiX code?

**Comment by adtzlr** [comment]
Hi. Honestly - I have no idea, I never used calculix. Do you know how to assign a user material to a mesh and how to compile Fortran subroutines within a calculix run? Best regards, Andreas

**Comment by nithinadidela** [comment]
Hi. I know it can be done using abaqus subroutines. I don't have any idea how to do that. I have seen you mention about abaqus subroutines in your webpage. Do you have any idea how to assign it in abaqus?

**Comment by adtzlr** [comment]
As there were no further replies I'll close this issue. Feel free to open it again.
